- id: renovate-config-validator
  name: renovate-config-validator
  description: Validate Renovate config
  language: node
  language_version: lts
  additional_dependencies: [renovate@40.12.3]
  entry: renovate-config-validator
  files: '(^|/).?renovate(?:rc)?(?:\.json5?)?$'
