- id: renovate-config-validator
  name: renovate-config-validator
  description: Validate Renovate config
  language: node
  additional_dependencies: [renovate@37.286.0]
  entry: renovate-config-validator
  files: '((^|/).?renovate(?:rc)?(?:\.json5?)?|^config.js)$'
